// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"battlePlugin","status":true,"description":"Version 0.0.1 - 16-10-2017 - A simple plugin that adds Active Turn Battles, Combo Attacks, and an energy mechanic to the battle system.  For faster development the built in Tp values are used as energy.","parameters":{"ATB Gauge Color 1":"","ATB Gauge Color 2":"","ATB Gauge Color 3":"","ATB Gauge Transparency":"1.0","TP Max Value":"5"}}
];
